---
- name: playbook para configurar NFS en CentOS
  hosts: centos
  become: yes

  vars:
    var_nfs_shared: /var/nfs_shared
    var_nfs_export: "/var/nfs_shared *(rw,sync,no_root_squash,no_subtree_check)"

  tasks:
   - name: Instalacion paquete nfs
     ansible.builtin.dnf:
      name: nfs-utils
      state: present

   - name: Verificar servicio nfs iniciado y habilitado
     ansible.builtin.systemd_service:
      name: nfs-server
      state: started
      enabled: true

   - name: Habilitar puerto en el Firewall
     ansible.posix.firewalld:
       port: 2049/tcp
       permanent: yes
       state: enabled
       immediate: yes

   - name: Carpeta compartida
     ansible.builtin.file:
      path: "{{ var_nfs_shared }}"
      state: directory
      owner: nobody
      group: nobody
      mode: '0777'

   - name: Garantiza que la linea de exportacion exista
     ansible.builtin.lineinfile:
      path: /etc/exports
      line: "{{ var_nfs_export }}"
      state: present
     notify: reload_export

  handlers:
    - name: reload_export
      command: exportfs -r

